[build]
  command = "npm run build:ssr" # The command to build the Angular app for SSR
  functions = "netlify/functions" # This is where the SSR serverless functions will be placed
  publish = "dist/angular-forms/browser" # The folder with your static files for the browser

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "npm run start"  # Command to start your development server
  port = 3000               # Port that the dev server will be listening on
  publish = "dist"           # The folder with the static content for the dev server

# More info on configuring this file: https://ntl.fyi/file-based-build-config
